import { getPostBySlug, getAllPosts, categoryLabels } from '@/lib/posts'
import { notFound } from 'next/navigation'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import PostCard from '@/components/PostCard'
import { format } from 'date-fns'
import { sr } from 'date-fns/locale'
import type { Metadata } from 'next'

// Next.js 15: params is a Promise
type Props = { params: Promise<{ slug: string }> }

export async function generateStaticParams() {
  return getAllPosts().map(p => ({ slug: p.slug }))
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params
  const post = await getPostBySlug(slug)
  if (!post) return {}
  return {
    title: post.title,
    description: post.excerpt,
    openGraph: {
      title: post.title,
      description: post.excerpt,
      ...(post.coverImage && { images: [{ url: post.coverImage }] }),
    },
  }
}

export default async function BlogPostPage({ params }: Props) {
  // Await params — required in Next.js 15
  const { slug } = await params
  const post = await getPostBySlug(slug)
  if (!post) notFound()

  const all = getAllPosts()
  const related = all.filter(p => p.slug !== post.slug && p.category === post.category).slice(0, 3)

  const catLabel = categoryLabels[post.category]?.sr ?? post.category
  let dateFormatted = post.date
  try { dateFormatted = format(new Date(post.date), 'd. MMMM yyyy.', { locale: sr }) } catch {}

  return (
    <>
      <Navbar />
      <main style={{ background: '#0A0A0A', minHeight: '100vh' }}>

        {/* Hero image */}
        <div style={{ position: 'relative', height: '460px', overflow: 'hidden', background: post.coverImage ? `url(${post.coverImage}) center/cover no-repeat` : 'linear-gradient(135deg,#1A0505,#0A0A0A)' }}>
          <div style={{ position: 'absolute', top: 0, left: 0, bottom: 0, width: '5px', background: '#EF0107', zIndex: 2 }} />
          <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to top,rgba(10,10,10,1) 0%,rgba(10,10,10,.5) 60%,rgba(10,10,10,.15) 100%)' }} />
          <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, padding: '2.5rem 2rem', maxWidth: '900px', margin: '0 auto' }}>
            <span style={{ fontFamily: "'Barlow Condensed',sans-serif", fontWeight: 700, fontSize: '0.65rem', letterSpacing: '0.15em', textTransform: 'uppercase', color: '#EF0107', display: 'block', marginBottom: '0.75rem' }}>{catLabel}</span>
            <h1 style={{ fontFamily: "'Playfair Display',serif", fontWeight: 900, fontSize: 'clamp(1.8rem,4vw,2.8rem)', color: '#fff', lineHeight: 1.15, marginBottom: '1rem', maxWidth: '700px' }}>{post.title}</h1>
            <span style={{ fontFamily: "'Barlow Condensed',sans-serif", fontSize: '0.7rem', letterSpacing: '0.1em', color: '#555', textTransform: 'uppercase' }}>{dateFormatted}</span>
          </div>
        </div>

        {/* Article */}
        <div style={{ maxWidth: '740px', margin: '0 auto', padding: '3rem 1.5rem' }}>
          {post.excerpt && (
            <p style={{ fontFamily: "'Playfair Display',serif", fontSize: '1.2rem', fontStyle: 'italic', color: '#999', lineHeight: 1.7, borderLeft: '3px solid #9C824A', paddingLeft: '1.5rem', marginBottom: '3rem' }}>
              {post.excerpt}
            </p>
          )}
          {/* contentHtml generated by remark — safe server-side HTML */}
          <div className="article-body" dangerouslySetInnerHTML={{ __html: post.contentHtml }} />
        </div>

        {/* Related posts */}
        {related.length > 0 && (
          <section style={{ maxWidth: '1200px', margin: '0 auto', padding: '0 1.5rem 4rem' }}>
            <div style={{ borderTop: '1px solid #1C1C1C', paddingTop: '3rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '2rem' }}>
                <span style={{ display: 'block', width: '32px', height: '3px', background: '#EF0107', flexShrink: 0 }} />
                <span style={{ fontFamily: "'Barlow Condensed',sans-serif", fontWeight: 700, fontSize: '0.65rem', letterSpacing: '0.2em', textTransform: 'uppercase', color: '#EF0107' }}>Slični tekstovi</span>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(280px,1fr))', gap: '1.5rem' }}>
                {related.map(p => <PostCard key={p.slug} post={p} size="medium" />)}
              </div>
            </div>
          </section>
        )}

      </main>
      <Footer />
    </>
  )
}
